name = "DepolarizingAnticonformity"
uuid = "8043e2db-dd88-4f59-8661-d5e52683c9a3"
authors = ["lipiecki <arkadiusz.lipiecki@pwr.edu.pl>"]
version = "0.1.0"

[deps]
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
DiffEqCallbacks = "4.2.2"
DifferentialEquations = "7.15.0"
JLD2 = "0.5.9"
Plots = "1.40.9"
